name: .NET Core

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - Filters: "HawkuFilters"
          - Filters: "DevocubFilters"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Filters Build
      run: dotnet build ${{ matrix.Filters }}/${{ matrix.Filters }}.csproj -o ./build

    - name: Upload Filters artifact
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.Filters }}
        path: build/${{ matrix.Filters }}.dll
